spring:
  application:
    name: location-processor
  data:
    mongodb:
      uri:
      database: product
      collection: location
      proximity-radius-meters: 20

kafka:
  bootstrap-servers: localhost:9092
  topic:
    cart-locations: cart-locations
    cart-recommendations: cart-recommendations

  consumer:
    group-id: location-processor-group
    key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    auto-offset-reset: earliest
    enable-auto-commit: false

  producer:
    key-serializer: org.apache.kafka.common.serialization.StringSerializer
    value-serializer: org.apache.kafka.common.serialization.StringSerializer
    acks: all
    retries: 3
    enableIdempotence: true

logging:
  level:
    root: INFO
    com.smartcart.locationprocessor: DEBUG
    org.springframework.kafka: INFO
    com.azure.cosmos: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"